#!/bin/sh

focused_border_colour    : #ffffff
unfocused_border_colour  : #2f2f2f
swap_border_colour       : #eeeeee

exec			: "sxbar"
gaps                    : 7
border_width            : 3
master_width            : 60 # Percentage of screen width
resize_master_amount    : 1
resize_stack_amount     : 20
move_window_amount      : 10
resize_window_amount    : 20
snap_distance           : 5
motion_throttle         : 60 # Set to screen refresh rate for smoothest motions
should_float            : "pcmanfm", "obs"
new_win_focus           : true
warp_cursor             : true
floating_on_top         : true
new_win_master          : true
can_swallow             : "st"
can_be_swallowed        : "mpv", "sxiv"
start_fullscreen        : "mpv", "vlc"

# Commands must be surrounded with ""
# Functions calls don't need this
mod_key : super

bind : alt + q : "st"
bind : mod + b : "qutebrowser"
bind : mod + d : "rofi -show drun"
bind : Print :  "bash -c 'xnap | pnmtopng | tee ~/Pictures/screenshots/$(date +%Y-%m-%d_%H-%M).png | xclip -selection clipboard -t image/png'"

# Volume Controlling (with wpctl)

bind : XF86AudioRaiseVolume : "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
bind : XF86AudioLowerVolume : "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
bind : XF86AudioMute : "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"

# Window Management
call : mod + c : close_window 
call : mod + x : centre_window 
call : mod + shift + e : quit 
call : mod + m : toggle_monocle

# Focus Movement:
call : mod + i : focus_next
call : mod + k : focus_prev

# Monitor Focus:
call : mod + comma : focus_prev_mon
call : mod + period : focus_next_mon

# Move Window Between Monitors:
call : mod + shift + comma : move_prev_mon
call : mod + shift + period : move_next_mon

# Master/Stack Movement
call : mod + shift + i : master_next
call : mod + shift + k : master_prev

# Master Area Resize
call : mod + o : master_increase
call : mod + l : master_decrease

# Stack Window Resize
call : mod + shift + o : stack_increase
call : mod + shift + l : stack_decrease

# Keyboard Window Management
call : mod + Up : move_win_up
call : mod + Down : move_win_down
call : mod + Left : move_win_left
call : mod + Right : move_win_right

call : mod + shift + Up : resize_win_up
call : mod + shift + Down : resize_win_down
call : mod + shift + Left : resize_win_left
call : mod + shift + Right : resize_win_right

# Gaps 
call : mod + equal : increase_gaps
call : mod + minus : decrease_gaps

# Floating/Fullscreen
call : mod + space : toggle_floating
call : mod + shift + space : global_floating
call : mod + shift + f : fullscreen

# Reload Config
call : mod + r : reload_config

# Scratchpads
scratchpad : mod + alt + 1 : create 1
scratchpad : mod + alt + 2 : create 2
scratchpad : mod + alt + 3 : create 3
scratchpad : mod + alt + 4 : create 4

scratchpad : mod + ctrl + 1 : toggle 1
scratchpad : mod + ctrl + 2 : toggle 2
scratchpad : mod + ctrl + 3 : toggle 3
scratchpad : mod + ctrl + 4 : toggle 4

scratchpad : mod + alt + shift + 1 : remove 1
scratchpad : mod + alt + shift + 2 : remove 2
scratchpad : mod + alt + shift + 3 : remove 3
scratchpad : mod + alt + shift + 4 : remove 4

# Workspaces (1-9)
workspace : mod + 1          : move 1
workspace : mod + shift + 1  : swap 1
workspace : mod + 2          : move 2
workspace : mod + shift + 2  : swap 2
workspace : mod + 3          : move 3
workspace : mod + shift + 3  : swap 3
workspace : mod + 4          : move 4
workspace : mod + shift + 4  : swap 4
workspace : mod + 5          : move 5
workspace : mod + shift + 5  : swap 5
workspace : mod + 6          : move 6
workspace : mod + shift + 6  : swap 6
workspace : mod + 7          : move 7
workspace : mod + shift + 7  : swap 7
workspace : mod + 8          : move 8
workspace : mod + shift + 8  : swap 8
workspace : mod + 9          : move 9
workspace : mod + shift + 9  : swap 9
